<a href="https://colab.research.google.com/github/atakanberkyilmaz/Hafta3VeriOnIslemeEncoding/blob/main/Hafta_3_Veri_%C3%96n_%C4%B0%C5%9Fleme_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Veri Ön işleme; Encoding; Kayıp veri analizi

In [ ]:
#Liste 6.1
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Colab\ Notebooks
veriseti = pd.read_excel('VeriOnIsleme.xlsx', 'Sayfa1')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Colab Notebooks


/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [ ]:
#Liste 6.2
X = veriseti.iloc[:, :-1].values
y = veriseti.iloc[:, 5].values

In [ ]:
#Liste 6.3
from sklearn.impute import SimpleImputer
yaklasikDeger= SimpleImputer(missing_values=np.nan, strategy='mean')

In [ ]:
#Liste 6.4
yaklasikDeger=yaklasikDeger.fit(X[:,1:6])
X[:,1:6]=yaklasikDeger.transform(X[:,1:6])
print(X)
print(yaklasikDeger.statistics_)

[['Ev' 136861.0 87.0 1075.6 7.9]
 ['Ev' 178000.0 50.8 515.2 2.9]
 ['Ev' 156534.0 58.4 909.0692307692308 4.0]
 ['Otel' 62370.0 110.1 517.0 8.3]
 ['Otel' 204900.0 98.9 1540.3 6.315384615384616]
 ['Ofis' 105505.0 104.1 902.1 8.5]
 ['Ofis' 374958.0 65.0 1891.7 6.2]
 ['Otel' 93150.0 82.57692307692307 672.1 7.2]
 ['Ev' 214543.0 39.3 561.6 2.7]
 ['Ofis' 81986.0 65.4 390.5 4.8]
 ['Ofis' 71900.0 99.3 553.4 7.7]
 ['Ofis' 152532.0 84.1 949.8 6.2]
 ['Otel' 190440.0 113.8 1483.3 7.8]
 ['Ofis' 97230.0 97.3 765.3 7.9]]
[1.51493500e+05 8.25769231e+01 9.09069231e+02 6.31538462e+00]


In [ ]:
#Liste 6.5
import pandas as pd
X = veriseti.iloc[:, :-1].values
y = veriseti.iloc[:, 5].values
from sklearn.impute import SimpleImputer
yaklasikDeger= SimpleImputer(missing_values=np.nan, strategy='mean')
yaklasikDeger=yaklasikDeger.fit(X[:,1:6])
X[:,1:6]=yaklasikDeger.transform(X[:,1:6])
print(X)
print(yaklasikDeger.statistics_)

[['Ev' 136861.0 87.0 1075.6 7.9]
 ['Ev' 178000.0 50.8 515.2 2.9]
 ['Ev' 156534.0 58.4 909.0692307692308 4.0]
 ['Otel' 62370.0 110.1 517.0 8.3]
 ['Otel' 204900.0 98.9 1540.3 6.315384615384616]
 ['Ofis' 105505.0 104.1 902.1 8.5]
 ['Ofis' 374958.0 65.0 1891.7 6.2]
 ['Otel' 93150.0 82.57692307692307 672.1 7.2]
 ['Ev' 214543.0 39.3 561.6 2.7]
 ['Ofis' 81986.0 65.4 390.5 4.8]
 ['Ofis' 71900.0 99.3 553.4 7.7]
 ['Ofis' 152532.0 84.1 949.8 6.2]
 ['Otel' 190440.0 113.8 1483.3 7.8]
 ['Ofis' 97230.0 97.3 765.3 7.9]]
[1.51493500e+05 8.25769231e+01 9.09069231e+02 6.31538462e+00]


In [ ]:
#Liste 6.6
import pandas as pd
from sklearn.preprocessing import LabelEncoder
veriseti = pd.read_excel('VeriOnIsleme.xlsx', 'Sayfa1')

X = veriseti.iloc[:, :-1].values
y = veriseti.iloc[:, 5].values

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [ ]:
#Liste 6.7
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print (X)

[[0 136861 87.0 1075.6 7.9]
 [0 178000 50.8 515.2 2.9]
 [0 156534 58.4 nan 4.0]
 [2 62370 110.1 517.0 8.3]
 [2 204900 98.9 1540.3 nan]
 [1 105505 104.1 902.1 8.5]
 [1 374958 65.0 1891.7 6.2]
 [2 93150 nan 672.1 7.2]
 [0 214543 39.3 561.6 2.7]
 [1 81986 65.4 390.5 4.8]
 [1 71900 99.3 553.4 7.7]
 [1 152532 84.1 949.8 6.2]
 [2 190440 113.8 1483.3 7.8]
 [1 97230 97.3 765.3 7.9]]


In [ ]:
#Liste 6.8
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
veriseti = pd.read_excel('VeriOnIsleme.xlsx', 'Sayfa1')

X = veriseti.iloc[:, :-1].values
y = veriseti.iloc[:, 5].values

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

columnTransformer_X = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = columnTransformer_X.fit_transform(X)

print (X)

[[1.0 0.0 0.0 136861 87.0 1075.6 7.9]
 [1.0 0.0 0.0 178000 50.8 515.2 2.9]
 [1.0 0.0 0.0 156534 58.4 nan 4.0]
 [0.0 0.0 1.0 62370 110.1 517.0 8.3]
 [0.0 0.0 1.0 204900 98.9 1540.3 nan]
 [0.0 1.0 0.0 105505 104.1 902.1 8.5]
 [0.0 1.0 0.0 374958 65.0 1891.7 6.2]
 [0.0 0.0 1.0 93150 nan 672.1 7.2]
 [1.0 0.0 0.0 214543 39.3 561.6 2.7]
 [0.0 1.0 0.0 81986 65.4 390.5 4.8]
 [0.0 1.0 0.0 71900 99.3 553.4 7.7]
 [0.0 1.0 0.0 152532 84.1 949.8 6.2]
 [0.0 0.0 1.0 190440 113.8 1483.3 7.8]
 [0.0 1.0 0.0 97230 97.3 765.3 7.9]]


/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [ ]:
#Liste 6.9
if Bina_Tipi==0:
    print("Ev")
elif Bina_Tipi==1:
    print("Ofis")
elif Bina_Tipi==2:
    print("Otel")

NameError: name 'Bina_Tipi' is not defined